included:
  - README.md
  - SyncConnectionStateErrorReset
  - AnalyticsTelemetricsData
  - OfflineLoginRealmAccess
  - AppleSignInAuthentication
  - InAppPurchasesAtlasAppServices
type_name:
  allowed_symbols:
    - _
identifier_name:
  allowed_symbols:
    - _
